version: "3"
services:
  csvtocsvw_flask:
    build: .
    container_name: CSVToCSVW_with_Flask
    volumes:
      #- .:/src
    ports:
      - 5001:5000
    restart: always
    networks:
      - CSVToCSVW

networks:
  CSVToCSVW:
    name: CSVToCSVW
    driver: bridge
