version: "3"
services:
  csvtocsvw:
    build: .
    container_name: csvtocsvw
    environment:
      APP_MODE: development
    volumes:
      - ./:/src
    ports:
      - 5004:5000
    restart: always
    networks:
      - csvtocsvw_net

networks:
  csvtocsvw_net:
    name: csvtocsvw_net
    driver: bridge
