version: "3"
services:
  csvtocsvw:
    build: .
    container_name: csvtocsvw
    #volumes:
      #- .:/src
    ports:
      - 5001:5000
    restart: always
    networks:
      - csvtocsvw_net

networks:
  csvtocsvw_net:
    name: csvtocsvw_net
    driver: bridge
