version: "3"
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "db_user"
      DB_MYSQL_PASSWORD: "db_password"
      DB_MYSQL_NAME: "db_name"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - db
    networks:
      CSVToCSVW:
        ipv4_address: 10.4.0.2

  db:
    image: 'jc21/mariadb-aria:latest'
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'db_rootpassword'
      MYSQL_DATABASE: 'database'
      MYSQL_USER: 'db_user'
      MYSQL_PASSWORD: 'db_password'
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      CSVToCSVW:
        ipv4_address: 10.4.0.3

  flask:
    build: .
    container_name: flask
    volumes:
      - ./src:/src
    expose:
      - "5000"
    ports:
      - 5000:5000
    restart: always
    networks:
      CSVToCSVW:
        ipv4_address: 10.4.0.4

networks:
  CSVToCSVW:
    driver: bridge
    ipam:
      config:
        - subnet: 10.4.0.0/16
