version: "3"
services:
  csvtocsvw:
    image: "ghcr.io/mat-o-lab/csvtocsvw:latest"
    container_name: "csvtocsvw"
    environment:
      APP_MODE: "development"
    volumes:
    #  - ./:/src
    ports:
      - ${APP_PORT}:5000
    restart: always
    networks:
      - csvtocsvw_net

networks:
  csvtocsvw_net:
    name: csvtocsvw_net
    driver: bridge
