# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish Docker image

on: [workflow_dispatch]

jobs:
  build:
    name: 'Build and push to ghcr.io'
    runs-on: ubuntu-latest
    steps:
      - name: "Build:checkout"
        uses: actions/checkout@v2
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          #context: "{{defaultContext}}:mysubdir"
          push: true
          tags: thhanke/csvtocsvw:latest
