name: TestExamples

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  WORKING_DIR: ./examples/

jobs:
  TestExamples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0        
      - name: run app
        run: |
          docker-compose up -d
          sleep 10
          docker ps -a
      - name: create csvw json-ld
        working-directory: ${{env.WORKING_DIR}}
        run: |
          for file in *.csv 
            do
              echo "$file"
              RESULT=$(curl -X POST "http://localhost:5001/api" -H  "accept: application/json" -H  "accept: application/json" -H  "Content-Type: application/json" -d "{\"data_url\":\"https://github.com/Mat-O-Lab/CSVToCSVW/raw/main/examples/$file\"}")
              FILENAME=$(echo $RESULT | jq -r '.filename')
              JSONLD=$(jq .filedata <<< "$RESULT")
              echo -e ${JSONLD} > $FILENAME
            done
      - name: Commit files # commit the output folder
        uses: EndBug/add-and-commit@v9
        with:
          message: 'updated example output'
          add: '*.* --force'
          cwd: './examples/'
